# Generated by Django 3.2.13 on 2022-07-12 01:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='primary_image',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Organization_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
        ),
    ]
