# Generated by Django 3.2.13 on 2022-07-15 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0008_eventparam'),
        ('organizations', '0003_auto_20220711_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('updater_id', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization', to='organizations.organization')),
            ],
        ),
    ]
