# Generated by Django 3.2.13 on 2022-07-23 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swap',
            name='new_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swap',
            name='old_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swap',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift', to='shifts.shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event', to='events.event'),
        ),
        migrations.AddField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='shift',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='swap',
            unique_together={('old_employee', 'shift')},
        ),
        migrations.AlterIndexTogether(
            name='swap',
            index_together={('old_employee', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('employee', 'event')},
        ),
        migrations.AlterIndexTogether(
            name='shift',
            index_together={('employee', 'event')},
        ),
    ]
