# Generated by Django 3.2.13 on 2022-07-22 20:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventparam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0004_auto_20220721_2317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('employee', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='swap',
            unique_together={('old_employee', 'shift')},
        ),
        migrations.AlterIndexTogether(
            name='shift',
            index_together={('employee', 'event')},
        ),
        migrations.AlterIndexTogether(
            name='swap',
            index_together={('old_employee', 'shift')},
        ),
    ]
