# Generated by Django 3.2.13 on 2022-07-12 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=254)),
                ('location', models.CharField(blank=True, max_length=254, null=True)),
                ('primary_image', models.UUIDField(blank=True, null=True)),
                ('recurrences', recurrence.fields.RecurrenceField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
                ('updater_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
