# Generated by Django 3.2.13 on 2022-07-10 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0004_user_group_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Group_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relationships.user_group')),
            ],
        ),
    ]
