# Generated by Django 3.2.13 on 2022-07-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0005_user_group_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_group',
            name='image',
        ),
    ]
