# Generated by Django 3.2.13 on 2022-07-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220709_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
